#:schema node_modules/wrangler/config-schema.json
name = "cf-remix-hono"
compatibility_date = "2024-05-12"
compatibility_flags = [ "nodejs_compat" ]

pages_build_output_dir = "build"

[vars]
MY_VAR = "Hello from Cloudflare"
